# TCL File Generated by Component Editor 11.0
# Fri Jun 03 11:25:24 IST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | LCD_Interface "1.7" TFT LCD Interface" v8.0
# | System Level Solutions 2011.06.03.11:25:24
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module LCD_Interface
# | 
set_module_property DESCRIPTION ""
set_module_property NAME LCD_Interface
set_module_property VERSION 8.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP SLS/Display
set_module_property AUTHOR "System Level Solutions"
set_module_property ICON_PATH sls_logo.jpg
set_module_property DISPLAY_NAME "1.7\" TFT LCD Interface"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE false
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ""
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock AvS_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment NATIVE
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset clock_reset
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 15
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitStates 200
set_interface_property avalon_slave readWaitTime 200
set_interface_property avalon_slave setupTime 10
set_interface_property avalon_slave timingUnits Nanoseconds
set_interface_property avalon_slave writeWaitStates 50
set_interface_property avalon_slave writeWaitTime 50

set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave AvS_address address Input 1
add_interface_port avalon_slave AvS_chipselect_n chipselect_n Input 1
add_interface_port avalon_slave AvS_read_n read_n Input 1
add_interface_port avalon_slave AvS_write_n write_n Input 1
add_interface_port avalon_slave AvS_readdata readdata Output 8
add_interface_port avalon_slave AvS_writedata writedata Input 8
# | 
# +-----------------------------------
