# TCL File Generated by Component Editor 11.0
# Mon May 23 10:23:15 IST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | DC_Motor_Controller "DC Motor Controller" v1.0
# | SLS 2011.05.23.10:23:15
# | pwm
# | 
# | E:/designs/altera/altra-p-bmsob-motcon/trunk/soc/rtl/pwm/pwm_avalon_interface.v
# | 
# |    ./pwm_avalon_interface.v syn, sim
# |    ./pwm_register_file.v syn, sim
# |    ./pwm_task_logic.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module DC_Motor_Controller
# | 
set_module_property DESCRIPTION pwm
set_module_property NAME DC_Motor_Controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "SLS/DC Motor"
set_module_property AUTHOR SLS
set_module_property ICON_PATH hdl/sls_logo.jpg
set_module_property DISPLAY_NAME "DC Motor Controller"
set_module_property TOP_LEVEL_HDL_FILE hdl/pwm_avalon_interface.v
set_module_property TOP_LEVEL_HDL_MODULE pwm_avalon_interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME "pwm_avalon_interface"
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/pwm_avalon_interface.v {SYNTHESIS SIMULATION}
add_file hdl/pwm_register_file.v {SYNTHESIS SIMULATION}
add_file hdl/pwm_task_logic.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter clock_divide_reg_init STD_LOGIC_VECTOR 0
set_parameter_property clock_divide_reg_init DEFAULT_VALUE 0
set_parameter_property clock_divide_reg_init DISPLAY_NAME clock_divide_reg_init
set_parameter_property clock_divide_reg_init TYPE STD_LOGIC_VECTOR
set_parameter_property clock_divide_reg_init UNITS None
set_parameter_property clock_divide_reg_init ALLOWED_RANGES 0:17179869183
set_parameter_property clock_divide_reg_init AFFECTS_GENERATION false
set_parameter_property clock_divide_reg_init HDL_PARAMETER true
add_parameter duty_cycle_reg_init STD_LOGIC_VECTOR 0
set_parameter_property duty_cycle_reg_init DEFAULT_VALUE 0
set_parameter_property duty_cycle_reg_init DISPLAY_NAME duty_cycle_reg_init
set_parameter_property duty_cycle_reg_init TYPE STD_LOGIC_VECTOR
set_parameter_property duty_cycle_reg_init UNITS None
set_parameter_property duty_cycle_reg_init ALLOWED_RANGES 0:17179869183
set_parameter_property duty_cycle_reg_init AFFECTS_GENERATION false
set_parameter_property duty_cycle_reg_init HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 avalon_chip_select chipselect Input 1
add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 write_data writedata Input 32
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 read_data readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink resetn reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end pwm_out export Output 1
# | 
# +-----------------------------------
