# TCL File Generated by Component Editor 11.0
# Wed Jul 13 14:00:26 IST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | pid_controller_top "PID Controller" v1.0
# | System Level Solutions 2011.07.13.14:00:26
# | Avalon Based PID Controller
# | 
# | E:/designs/altera/altra-p-bmsob-motcon/trunk/soc/rtl/PID/hdl/pid_controller_top.v
# | 
# |    ./hdl/pid_controller.v syn, sim
# |    ./hdl/pid_controller_top.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module pid_controller_top
# | 
set_module_property DESCRIPTION "Avalon Based PID Controller"
set_module_property NAME pid_controller_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP SLS/PID
set_module_property AUTHOR "System Level Solutions"
set_module_property ICON_PATH sls_logo.jpg
set_module_property DISPLAY_NAME "PID Controller"
set_module_property TOP_LEVEL_HDL_FILE hdl/pid_controller_top.v
set_module_property TOP_LEVEL_HDL_MODULE pid_controller_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME pid_controller_top
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/pid_controller.v {SYNTHESIS SIMULATION}
add_file hdl/pid_controller_top.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter Max STD_LOGIC_VECTOR 65535
set_parameter_property Max DEFAULT_VALUE 65535
set_parameter_property Max DISPLAY_NAME Max
set_parameter_property Max WIDTH 18
set_parameter_property Max TYPE STD_LOGIC_VECTOR
set_parameter_property Max ENABLED false
set_parameter_property Max UNITS None
set_parameter_property Max ALLOWED_RANGES 0:262143
set_parameter_property Max AFFECTS_GENERATION false
set_parameter_property Max HDL_PARAMETER true
add_parameter Min STD_LOGIC_VECTOR 0
set_parameter_property Min DEFAULT_VALUE 0
set_parameter_property Min DISPLAY_NAME Min
set_parameter_property Min WIDTH 18
set_parameter_property Min TYPE STD_LOGIC_VECTOR
set_parameter_property Min ENABLED false
set_parameter_property Min UNITS None
set_parameter_property Min ALLOWED_RANGES 0:262143
set_parameter_property Min AFFECTS_GENERATION false
set_parameter_property Min HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 avalon_chip_select chipselect Input 1
add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 write_data writedata Input 32
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 read_data readdata Output 32
# | 
# +-----------------------------------
