# TCL File Generated by Component Editor 11.0
# Thu May 26 10:27:40 IST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | i2c_master_top "I2C master" v1.0
# | opencore 2011.05.26.10:27:40
# | I2C master
# | 
# | E:/designs/altera/altra-p-bmsob-motcon/trunk/soc/syn/ref_design/sys_q11_qsys_BeInMotion/ip/opencore_i2c/hdl/i2c_master_top.v
# | 
# |    ./i2c_master_bit_ctrl.v syn, sim
# |    ./i2c_master_byte_ctrl.v syn, sim
# |    ./i2c_master_top.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module i2c_master_top
# | 
set_module_property DESCRIPTION "I2C master"
set_module_property NAME i2c_master_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP SLS/OpenCores
set_module_property AUTHOR opencore
set_module_property DISPLAY_NAME "I2C master"
set_module_property TOP_LEVEL_HDL_FILE hdl/i2c_master_top.v
set_module_property TOP_LEVEL_HDL_MODULE i2c_master_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME i2c_master_top
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/i2c_master_bit_ctrl.v {SYNTHESIS SIMULATION}
add_file hdl/i2c_master_byte_ctrl.v {SYNTHESIS SIMULATION}
add_file hdl/i2c_master_top.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock wb_clk_i clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment NATIVE
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 wb_adr_i address Input 3
add_interface_port avalon_slave_0 wb_dat_i writedata Input 8
add_interface_port avalon_slave_0 wb_dat_o readdata Output 8
add_interface_port avalon_slave_0 wb_we_i write Input 1
add_interface_port avalon_slave_0 wb_stb_i chipselect Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink arst_i reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink

set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender wb_inta_o irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end scl_pad_i export Input 1
add_interface_port conduit_end scl_pad_o export Output 1
add_interface_port conduit_end scl_padoen_o export Output 1
add_interface_port conduit_end sda_pad_i export Input 1
add_interface_port conduit_end sda_pad_o export Output 1
add_interface_port conduit_end sda_padoen_o export Output 1
# | 
# +-----------------------------------
